defaults: &defaults
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 25
  database: birthday_development
  username: <%= ENV['USERNAME'] %>
  password:
  min_messages: warning
  host: localhost

development:
  <<: *defaults

test: &test
  <<: *defaults
  database: birthday_test

production:
  <<: *defaults
  database: birthday_test
  password: <%= ENV['RUBY-GETTING-STARTED_DATABASE_PASSWORD'] %>

